In [1]:

import pandas as pd


#let's make some lazy haplotypes

generator1 = ["1", "0"]


haplo = [a+b+c+d for a in generator1 for b in generator1 for c in generator1 
              for d in generator1]


for hap in haplo:
    print(hap)
#seems to work as planned, generated 32 seqs for us


numseq = list(range(len(haplo)))


hapdict = {}

for num in numseq:
    hapdict[haplo[num]] = 1 / float(len(haplo))



#Haplotype dictionary enabled for later shenanigans


1111
1110
1101
1100
1011
1010
1001
1000
0111
0110
0101
0100
0011
0010
0001
0000


Haplotypes for our genotypes


0011

0011 + 0000,
0010 + 0001



2102

1101 + 1001



0012

0011 + 0001



2112

1001 + 1111,
1101 + 1011




0102

0001 + 0101

In [2]:

counter = 0


while counter < 1000:


    #Expectation

    #g1 = "0011"
    g11 = (hapdict["0011"] * hapdict["0000"])
    g12 = (hapdict["0010"] * hapdict["0001"])
    #raw odds
    #print(g11)

    g1sum = g11 + g12
    g11 = g11 / g1sum
    g12 = g12 / g1sum
    #normalised odds
    #print(g11)



    #g2 = "2102"
    g21 = (hapdict["1101"] * hapdict["1001"])
    #raw odds
    #print(g21)

    g2sum = g21
    g21 = g21 / g2sum
    #normalised odds
    #print(g21)





    #g3 = "0012"
    g31 = (hapdict["0011"] * hapdict["0001"])
    #raw odds
    #print(g31)

    g3sum = g31
    g31 = g31 / g3sum
    #normalised odds
    #print(g31)





    #g4 = "2112"
    g41 = (hapdict["1001"] * hapdict["1111"])
    g42 = (hapdict["1101"] * hapdict["1011"])
    #raw odds
    #print(g41)

    g4sum = g41 + g42
    g41 = g41 / g4sum
    g42 = g42 / g4sum
    #normalised odds
    #print(g41)





    #g5 = "0102"
    g51 = (hapdict["0001"] * hapdict["0101"])
    #raw odds
    #print(g51)

    g5sum = g51
    g51 = g51 / g5sum
    #normalised odds
    #print(g51)


    #Maximisation

    #0011(2) g11, g31
    #0000(1) g11
    #0010(1) g12
    #0001(3) g12, g31, g51
    #1101(2) g21, g42
    #1001(2) g21, g41
    #1111(1) g41
    #1011(1) g42
    #0101(1) g51
    #No. occurances of each haplotype + matching variable

    usedhaps = ("0011", "0000", "0010", "0001", "1101", "1001", "1111", "1011", "0101")
    #print(haplo)


    hapdict["1111"] = g41 / float(10)

    hapdict["1110"] = 0 / float(10)

    hapdict["1101"] = (g21 + g41) / float(10)

    hapdict["1100"] = 0 / float(10)

    hapdict["1011"] = g42 / float(10)

    hapdict ["1010"] = 0 / float(10)

    hapdict ["1001"] = (g21 + g41) / float(10)

    hapdict["1000"] = 0 / float(10)

    hapdict["0111"] = 0 / float(10)

    hapdict["0110"] = 0 / float(10)

    hapdict["0101"] = g51 / float(10)

    hapdict["0100"] = 0 / float(10)

    hapdict["0011"] = (g11 + g31) / float(10)

    hapdict["0010"] = g12 / float(10)

    hapdict["0001"] = (g12 + g31 + g51) / float(10)

    hapdict["0000"] = g11 / float(10)


    #print(hapdict)
    counter += 1




#sum(dict.values(hapdict))
#sums to 1, as we'd like to see

hapframe = pd.Series(hapdict  , name = "Haplotypes")

print(hapframe)

1111    0.05
1110    0.00
1101    0.15
1100    0.00
1011    0.05
1010    0.00
1001    0.15
1000    0.00
0111    0.00
0110    0.00
0101    0.10
0100    0.00
0011    0.10
0010    0.10
0001    0.30
0000    0.00
Name: Haplotypes, dtype: float64


In [3]:
#Maximum likelihoods

#0011
print("#1. 0011 Likelihoods")
g11prob = hapdict["0011"] * hapdict["0000"]
g12prob = hapdict["0010"] * hapdict["0001"]
print("0011 + 0000: ", g11prob)
print("0010 + 0001: ", g12prob)
print("")

#2102
print("#2. 2102 Likelihoods")
g21prob = hapdict["1101"] * hapdict["1001"]
print("1101 + 1001 :", g21prob)
print("")


#0012
print("#3. 0012 Likelihoods")
g31prob = hapdict["0011"] * hapdict["0001"]
print("0011 + 0001: ", g31prob)
print("")


#2112
print("#4. 2112 Likelihoods")
g41prob = hapdict["1001"] * hapdict["1111"]
g42prob = hapdict["1101"] * hapdict["1011"]
print("1001 + 1111: ", g41prob)
print("1101 + 1011: ", g42prob)
print("")


#0102
print("#5. 0102 Likelihoods")
g51prob = hapdict["0001"] * hapdict["0101"]
print("0001 + 0101: ", g51prob)

print("Done")

#1. 0011 Likelihoods
0011 + 0000:  0.0
0010 + 0001:  0.03

#2. 2102 Likelihoods
1101 + 1001 : 0.0225

#3. 0012 Likelihoods
0011 + 0001:  0.03

#4. 2112 Likelihoods
1001 + 1111:  0.0075
1101 + 1011:  0.0075

#5. 0102 Likelihoods
0001 + 0101:  0.03
Done


From the above outputs, we can see that the most likely haplotypes for genotype 1 (0011) was 0010 + 0001, with 0011 + 0000 being completely eliminated.

For Genotypes 2, 3 and 5 there was only one outcome, that being 1101 + 1001, 0011 + 0001, and 0001 + 0101 respectively.

Despite our EM algorithm converging, it seems that genotype 4 has an equal likelihood of it being both possible haplotypes.